'use client';
import { useEffect, useRef, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import Link from 'next/link';
import gsap from 'gsap';
import { useWishlist } from '@/components/wishlist-provider';
import { useCatalogue } from '@/components/catalogue-provider';
import { ProductCard } from '@/components/product-card';
import { ResetPassword } from '@/components/reset-password';
import { AccountArt, AccountEmptyState, AccountIcon } from './ui';
import { AddressesView, OrdersView, ProfileView, RewardsCard, RewardsView, type AccountAddress, type AccountOrder, type Reward, type RewardSettings } from './views';
const sections = [{ id:'overview',label:'Overview',icon:'home' },{ id:'orders',label:'My Orders',icon:'products' },{ id:'wishlist',label:'Wishlist',icon:'heart' },{ id:'addresses',label:'Addresses',icon:'pin' },{ id:'profile',label:'Profile',icon:'profile' },{ id:'rewards',label:'Rewards',icon:'star' }] as const;
type Section = typeof sections[number]['id'];
export type DashboardProps = { email: string; profile: { name: string; phone: string } | null; addresses: AccountAddress[]; addressCount: number | null; orders: AccountOrder[]; orderCount: number | null; rewards: Reward[]; balance: number | null; settings: RewardSettings | null; errors: { profile: boolean; addresses: boolean; orders: boolean; rewards: boolean } };
function AccountSidebar({ section,select }: { section: Section; select: (section: Section) => void }) {
  const router = useRouter(); const [busy,setBusy] = useState(false); const [error,setError] = useState('');
  return <aside className="account-sidebar account-card"><h2>My SoftHaven</h2><nav aria-label="Account sections">{sections.map(item => <button key={item.id} type="button" aria-current={section === item.id ? 'page' : undefined} className={section === item.id ? 'is-active' : ''} onClick={() => select(item.id)}><AccountIcon name={item.icon} /><span>{item.label}</span></button>)}</nav><button className="account-signout" disabled={busy} onClick={async () => { if (busy) return; setBusy(true); setError(''); try { const response = await fetch('/api/auth', { method:'POST',headers:{ 'Content-Type':'application/json' },body:JSON.stringify({ action:'logout' }) }); if (!response.ok) throw new Error('Sign out failed'); router.replace('/account'); router.refresh(); } catch { setError('We couldn’t sign you out. Please try again.'); } finally { setBusy(false); } }}><AccountIcon name="logout" />{busy ? 'Signing out…' : 'Sign Out'}</button>{error && <p role="alert">{error}</p>}<div className="account-sidebar-art"><AccountArt kind="bunny" /><p>A little more<br />softness, always.</p><AccountIcon name="heart" /></div></aside>;
}
function AccountWelcome({ name }: { name?: string }) { const first = name?.trim().split(/\s+/)[0]; return <header className="account-welcome"><div className="account-welcome-copy"><p className="account-eyebrow">MY SOFTHAVEN <span /></p><h1>Welcome back{first ? `, ${first}` : ''} <span>♡</span></h1><p className="account-subtitle">Your little SoftHaven corner.</p><p className="account-welcome-description">Manage your orders, save your favourite companions and keep<br className="account-desktop-break" /> your details up to date — all in one place.</p></div><AccountArt className="account-hero-art" /></header>; }
function AccountStats({ data,select }: { data: DashboardProps; select: (section: Section) => void }) {
  const { ids } = useWishlist(); const [ready,setReady] = useState(false); useEffect(() => setReady(true),[]);
  const cards: { id:Section; title:string; value:number | string | null; suffix?:string; copy:string; icon:string }[] = [{ id:'orders',title:'Orders',value:data.orderCount,copy:'Track your cuddles',icon:'orders' },{ id:'rewards',title:'Reward Points',value:data.balance,suffix:'pts',copy:'Every order brings a little more joy',icon:'star' },{ id:'addresses',title:'Saved Addresses',value:data.addressCount,copy:'Ready for delivery',icon:'pin' },{ id:'wishlist',title:'Wishlist',value:ready ? ids.length : null,copy:'Your favourite companions',icon:'heart' }];
  return <section className="account-stats" aria-label="Account at a glance">{cards.map(card => <button key={card.id} className={`account-stat account-stat-${card.id}`} onClick={() => select(card.id)}><span className="account-stat-icon"><AccountIcon name={card.icon} /></span><span className="account-stat-copy"><span className="account-stat-label">{card.title}</span><strong>{card.value ?? '—'}{card.suffix && <small> {card.suffix}</small>}</strong><span className="account-stat-description">{card.copy}</span></span><span className="account-stat-arrow"><AccountIcon name="chevron" /></span></button>)}</section>;
}
function AccountPromo() { return <Link href="/shop" className="account-promo account-card"><AccountArt kind="friends" /><div><h2>Find your<br />next favourite<br />companion</h2><span className="account-button">Shop the collection <AccountIcon name="arrow" /></span></div></Link>; }
function WishlistView() { const { ids } = useWishlist(); const { products } = useCatalogue(); const saved = products.filter(product => ids.includes(product.id)); const [ready,setReady] = useState(false); useEffect(() => setReady(true),[]); return <section className="account-card account-wishlist"><h2>My favourite hugs ♡</h2><p>Saved on this browser, ready for your next visit.</p>{!ready ? <p role="status">Gathering your favourites…</p> : saved.length ? <div className="account-product-grid">{saved.map(product => <ProductCard key={product.id} product={product} />)}</div> : <AccountEmptyState wishlist />}{ready && ids.length > saved.length && <p className="account-muted">Some saved companions are no longer available in the collection.</p>}</section>; }
export function AccountDashboard(data: DashboardProps) {
  const params = useSearchParams(); const initial = params.get('section'); const [section,setSection] = useState<Section>(sections.some(s => s.id === initial) ? initial as Section : 'overview'); const root = useRef<HTMLDivElement>(null);
  function select(next: Section) { setSection(next); const url = new URL(window.location.href); if (next === 'overview') url.searchParams.delete('section'); else url.searchParams.set('section',next); window.history.pushState(null,'',url); }
  useEffect(() => { const value = params.get('section'); setSection(sections.some(s => s.id === value) ? value as Section : 'overview'); },[params]);
  useEffect(() => { const media = gsap.matchMedia(); media.add('(prefers-reduced-motion: no-preference)',() => { gsap.from(root.current?.querySelectorAll('.account-welcome, .account-stats, .account-content') ?? [], { y:16, duration:.5, stagger:.07, ease:'power2.out', clearProps:'transform' }); }); return () => media.revert(); },[]);
  const headings = { overview:'', orders:'My orders', wishlist:'Your favourite companions', addresses:'Your delivery details', profile:'A little about you', rewards:'My SoftHaven Rewards' };
  return <div className="account-dashboard" ref={root}><AccountSidebar section={section} select={select} /><div className="account-main"><AccountWelcome name={data.profile?.name} /><ResetPassword /><AccountStats data={data} select={select} /><div className="account-content" id="account-section" aria-live="polite">{section === 'overview' ? <div className="account-overview-grid"><section className="account-card account-recent"><div className="account-card-heading"><h2>Your recent cuddles</h2><button className="account-button account-button-small" onClick={() => select('orders')}>View all orders <AccountIcon name="arrow" /></button></div><OrdersView orders={data.orders} error={data.errors.orders} recent /></section><div className="account-right"><RewardsCard balance={data.balance} settings={data.settings} error={data.errors.rewards} onMore={() => select('rewards')} /><AccountPromo /></div></div> : <><div className="account-view-heading"><h2>{headings[section]}</h2>{section === 'orders' && <p>Every SoftHaven companion has a journey.</p>}</div>{section === 'orders' && <section className="account-card"><OrdersView orders={data.orders} error={data.errors.orders} count={data.orderCount} /></section>}{section === 'wishlist' && <WishlistView />}{section === 'profile' && <ProfileView profile={data.profile} email={data.email} error={data.errors.profile} />}{section === 'addresses' && <AddressesView addresses={data.addresses} error={data.errors.addresses} count={data.addressCount} />}{section === 'rewards' && <RewardsView rewards={data.rewards} balance={data.balance} settings={data.settings} error={data.errors.rewards} />}</>}</div></div></div>;
}
