'use client';
import { useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import Link from 'next/link';
import { formatPrice } from '@/lib/format';
import { AccountEmptyState, AccountIcon, AccountLoadError } from './ui';
export type AccountOrder = { id: string; order_number: number; total: number; status: string; payment_status: string; created_at: string; tracking_number?: string; shipping_provider?: string; order_items?: { name: string; image?: string; quantity: number }[] };
export type AccountAddress = { id: string; name: string; phone: string; address: string; city: string; district: string };
export type RewardSettings = { enabled: boolean; minimum_redemption: number; point_value: number; earn_per_currency: number; expiry_days: number | null };
export type Reward = { id: string; points: number; reason: string; created_at: string; expires_at?: string };
export function OrdersView({ orders, error, recent = false, count }: { orders: AccountOrder[]; error: boolean; recent?: boolean; count?: number | null }) {
  if (error) return <AccountLoadError />;
  if (!orders.length) return <AccountEmptyState />;
  const labels: Record<string,string> = { pending: 'Order received', confirmed: 'Confirmed', processing: 'Processing', packed: 'Packed', shipped: 'On the way', delivered: 'Delivered', cancelled: 'Cancelled', returned: 'Returned', refunded: 'Refunded' };
  return <div className="account-orders">{(recent ? orders.slice(0,3) : orders).map(order => <article className="account-order" key={order.id}><div className="account-order-top"><strong>SH-{order.order_number}</strong><span className={`account-status status-${order.status}`}>{labels[order.status] ?? order.status}</span></div><div className="account-order-products">{order.order_items?.slice(0,3).map((item,index) => <div key={index}>{item.image && <Image src={item.image} alt={item.name} width={54} height={54} unoptimized />}<span>{item.name}<small>Quantity {item.quantity}</small></span></div>)}</div><div className="account-order-bottom"><span><time dateTime={order.created_at}>{new Date(order.created_at).toLocaleDateString('en-LK', { timeZone: 'Asia/Colombo', day: 'numeric', month: 'short', year: 'numeric' })}</time><small>Payment: {order.payment_status.replaceAll('_',' ')}</small></span><strong>{formatPrice(order.total)}</strong><Link href={`/account/orders/${order.id}`}>View order <AccountIcon name="arrow" /></Link></div>{order.tracking_number && <p className="account-tracking">{order.shipping_provider}: {order.tracking_number}</p>}</article>)}{!recent && count != null && count > orders.length && <p>Showing your latest {orders.length} of {count} orders.</p>}</div>;
}
export function RewardsCard({ balance, settings, error, onMore }: { balance: number | null; settings: RewardSettings | null; error: boolean; onMore?: () => void }) {
  const threshold = settings?.enabled && settings.minimum_redemption > 0 ? settings.minimum_redemption : null;
  return <section className="account-card account-rewards"><h2>Your SoftHaven Rewards <span>✦</span></h2>{error ? <AccountLoadError /> : <><p className="account-points">{balance ?? '—'} <span>points</span></p>{threshold && balance != null ? <><progress aria-label="Progress to minimum reward redemption" value={Math.max(0,balance)} max={Math.max(threshold,balance)} /><p className="account-progress-caption">{balance} / {threshold} points{balance >= threshold ? ' · Ready to redeem' : ''}</p><div className="account-reward-rule"><AccountIcon name="star" /><div><strong>{threshold} points = {formatPrice(threshold * settings!.point_value)}</strong><p>Redeem your points at checkout.</p></div></div></> : <p className="account-muted">{settings?.enabled ? 'Your points are safely tucked away here.' : 'Your available balance will appear here. Reward redemption is currently unavailable.'}</p>}{onMore && <button className="account-text-button" onClick={onMore}>Learn more about rewards <AccountIcon name="arrow" /></button>}</>}</section>;
}
export function RewardsView({ rewards, balance, settings, error }: { rewards: Reward[]; balance: number | null; settings: RewardSettings | null; error: boolean }) { return <><RewardsCard balance={balance} settings={settings} error={error} />{!error && <section className="account-card account-history"><h2>Your points journey</h2>{settings?.enabled && <p>{settings.earn_per_currency > 0 ? `Earn ${settings.earn_per_currency} points for every LKR 1 of eligible order value.` : 'Points are awarded according to the store’s current rewards settings.'}{settings.expiry_days ? ` New points expire after ${settings.expiry_days} days.` : ''}</p>}{rewards.length ? rewards.map(r => <article key={r.id}><div><strong>{r.reason}</strong><small>{new Date(r.created_at).toLocaleDateString('en-LK', { timeZone: 'Asia/Colombo' })}</small></div><b>{r.points > 0 ? '+' : ''}{r.points} pts</b></article>) : <p className="account-muted">Your reward history will appear here when points are awarded or redeemed.</p>}</section>}</>; }
function useAccountSave() {
  const router = useRouter(); const [busy,setBusy] = useState(false); const [message,setMessage] = useState(''); const [failed,setFailed] = useState(false);
  async function save(body: Record<string,unknown>, success: string) { setBusy(true); setMessage(''); setFailed(false); try { const response = await fetch('/api/account', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error('Account save failed'); setMessage(success); router.refresh(); return true; } catch(error) { console.error('Account update failed',error); setFailed(true); setMessage('We couldn’t save this right now. Please try again.'); return false; } finally { setBusy(false); } }
  return { busy,message,failed,save };
}
export function ProfileView({ profile,email,error }: { profile: { name: string; phone: string } | null; email: string; error: boolean }) {
  const { busy,message,failed,save } = useAccountSave();
  if (error) return <AccountLoadError />;
  return <form className="account-card account-form" onSubmit={async e => { e.preventDefault(); if (busy) return; const data = new FormData(e.currentTarget); await save({ action: 'profile', name: data.get('name'), phone: data.get('phone') }, 'Profile updated ♡'); }}><h2>Personal details</h2><p>Keep your SoftHaven details up to date.</p><div className="account-fields"><label>Name<input name="name" autoComplete="name" defaultValue={profile?.name ?? ''} maxLength={150} /></label><label>Email<input type="email" value={email} readOnly autoComplete="email" /><small>Your sign-in email</small></label><label>Phone<input name="phone" type="tel" autoComplete="tel" defaultValue={profile?.phone ?? ''} maxLength={30} /></label></div><button className="account-button" disabled={busy}>{busy ? 'Saving…' : 'Save changes'}<AccountIcon name="check" /></button><p role={failed ? 'alert' : 'status'}>{message}</p></form>;
}
export function AddressesView({ addresses,error,count }: { addresses: AccountAddress[]; error: boolean; count: number | null }) {
  const [fieldErrors,setFieldErrors] = useState<Record<string,string>>({}); const [adding,setAdding] = useState(false); const [removing,setRemoving] = useState<string | null>(null); const { busy,message,failed,save } = useAccountSave();
  if (error) return <AccountLoadError />;
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (busy) return; const form = new FormData(e.currentTarget); if (await save({ action:'address', ...Object.fromEntries(form) },'Address saved ♡')) setAdding(false); }
  return <section className="account-card account-addresses"><div className="account-card-heading"><h2>Saved addresses</h2><button className="account-button" onClick={() => setAdding(!adding)} aria-expanded={adding}><AccountIcon name="plus" />{adding ? 'Close form' : 'Add new address'}</button></div><p>Your favourite companions need to know where to find you.</p><div className="account-address-grid">{addresses.map(a => <article key={a.id}><AccountIcon name="pin" /><h3>{a.name}</h3><p>{a.address}<br />{a.city}{a.district ? `, ${a.district}` : ''}</p><p>{a.phone}</p>{removing === a.id ? <div className="account-remove-confirm"><p>Remove this saved address?</p><button disabled={busy} className="account-text-button" onClick={async () => { await save({ action:'remove_address',id:a.id },'Address removed'); setRemoving(null); }}>Confirm removal</button><button disabled={busy} className="account-text-button" onClick={() => setRemoving(null)}>Keep address</button></div> : <button disabled={busy} className="account-text-button" onClick={() => setRemoving(a.id)}>Remove address</button>}</article>)}</div>{!addresses.length && !adding && <div className="account-address-empty"><AccountIcon name="pin" /><h3>A place for your next delivery.</h3><p>Add an address to make your next checkout a little easier.</p></div>}{count != null && count > addresses.length && <p>Showing {addresses.length} of {count} saved addresses.</p>}{adding && <form className="account-form" onSubmit={submit}><h3>Add a delivery address</h3><div className="account-fields address-fields">{['name','phone','address','city','district'].map(field => <label key={field} className={field === 'address' ? 'full' : ''}>{field === 'name' ? 'Recipient name' : field[0].toUpperCase()+field.slice(1)}<input name={field} aria-invalid={!!fieldErrors[field]} aria-describedby={fieldErrors[field] ? `address-${field}-error` : undefined} onInvalid={e => { const input = e.currentTarget; setFieldErrors(previous => ({ ...previous, [field]: input.validity.valueMissing ? 'Please complete this field.' : field === 'phone' ? 'Enter a phone number with at least 6 characters.' : 'Please check this value.' })); }} onChange={() => setFieldErrors(previous => ({ ...previous,[field]: '' }))} type={field === 'phone' ? 'tel' : 'text'} required={field !== 'district'} minLength={field === 'phone' ? 6 : field === 'address' ? 3 : undefined} maxLength={field === 'address' ? 500 : field === 'phone' ? 30 : 150} autoComplete={({ name:'name',phone:'tel',address:'street-address',city:'address-level2',district:'address-level1' } as Record<string,string>)[field]} />{fieldErrors[field] && <small id={`address-${field}-error`} className="account-field-error">{fieldErrors[field]}</small>}</label>)}</div><button disabled={busy} className="account-button">{busy ? 'Saving…' : 'Save address'}<AccountIcon name="check" /></button></form>}<p role={failed ? 'alert' : 'status'}>{message}</p></section>;
}
