import Link from 'next/link';
import { images, products } from '@/lib/data';
import { ProductCard } from '@/components/product-card';
import { SectionReveal } from '@/components/section-reveal';

export default function HomePage() { return <>
  <section className="hero"><div className="hero-copy"><span className="eyebrow">A softer way to celebrate</span><h1>Find Something <em>Soft</em> to Love.</h1><p>Thoughtful companions and heirloom keepsakes,<br/>curated for hugs, memories, and slow living.</p><div className="hero-actions"><Link className="primary-button" href="/shop">Shop the collection →</Link><Link className="text-button" href="/shop#collections">Explore the story　›</Link></div><div className="rating">★★★★★ <span>4.9 from 8,400+ collectors</span></div></div><div className="hero-showcase"><div className="floating-card left"><img src={images.bunny} alt="Celeste Cloud Bunny"/><span>Celeste Cloud Bunny</span></div><div className="hero-product"><span className="badge">Editor&apos;s pick</span><img src={images.bear} alt="The Aurelius Heritage Bear"/><div><h2>The Aurelius Heritage Bear</h2><span>$88.00　→</span></div></div><div className="floating-card right"><img src={images.gift} alt="A keepsake gift box"/><span>Gift-ready</span></div></div></section>
  <SectionReveal><div className="trust-row"><div>✦<strong>Premium Quality</strong><span>Made for better hugs</span></div><div>⌁<strong>Carefully Selected</strong><span>Curated with intention</span></div><div>◌<strong>Gift-Ready Box</strong><span>Beautifully wrapped</span></div><div>♧<strong>Secure Shopping</strong><span>Safe & simple checkout</span></div><div>✈<strong>Global Delivery</strong><span>Softness, worldwide</span></div></div></SectionReveal>
  <SectionReveal><section className="section" id="collections"><div className="section-heading"><div><span className="eyebrow">Made for every kind of feeling</span><h2>Our Most-Loved Collections</h2><p>From the timeless teddy to the unexpected companion,<br/>there&apos;s a softer side waiting for you.</p></div><Link className="text-button" href="/shop">View All Items →</Link></div><div className="collection-grid"><Link className="collection-card mint" href="/shop"><div><span className="eyebrow">01 / Classic</span><h3>Teddy Bear Collection</h3><p>Iconic silhouettes, made heirloom.</p><span>Explore Teddy Bears →</span></div><img src={images.bear} alt="Teddy bear collection"/></Link><Link className="collection-card blush" href="/shop"><div><span className="eyebrow">02 / Sentiment</span><h3>Love & Gifting</h3><p>Small gestures, softly remembered.</p><span>Shop for someone →</span></div><img src={images.heart} alt="Love and gifting collection"/></Link><Link className="collection-card blue" href="/shop"><div><span className="eyebrow">03 / Gentle</span><h3>Soft Animal Friends</h3><p>For every age and every mood.</p><span>Meet the friends →</span></div><img src={images.sloth} alt="Soft animal friends collection"/></Link><Link className="collection-card lavender" href="/shop"><div><span className="eyebrow">04 / Statement</span><h3>Large & Life-Size Plush</h3><p>Make room for a bigger hug.</p><span>See statement pieces →</span></div><img src={images.gift} alt="Large plush collection"/></Link></div></section></SectionReveal>
  <SectionReveal><section className="section"><div className="section-heading"><div><span className="eyebrow">The ones everyone keeps talking about</span><h2>SoftHaven Favourites</h2><p>A quiet edit of our most-loved companions.</p></div><span className="filter-pill">All Favourites　⌄</span></div><div className="product-grid">{products.map((product) => <ProductCard key={product.id} product={product}/>)}</div></section></SectionReveal>
  <SectionReveal><section className="better-hugs"><div><span className="eyebrow">Crafted for comfort</span><h2>Made for Better Hugs</h2><p>Every SoftHaven companion is thoughtfully designed to feel as good as it looks.</p><div className="detail-grid">{['Hypoallergenic Fibers','Double-Lock Seams','Micro-Glass Beads','Hand-Embroidered'].map((item, i) => <div key={item}><b>0{i + 1}</b><h3>{item}</h3><p>Gentle materials and considered finishing, made to last.</p></div>)}</div></div><blockquote>“The weight, the softness, the tiny details — it feels like a hug you can keep.”<cite>— Sophie, verified collector</cite></blockquote></section></SectionReveal>
  <SectionReveal><section className="gift-feature"><div className="section-heading"><div><span className="eyebrow">Choose by feeling</span><h2>Find the Perfect Soft Gift</h2><p>For birthdays, new beginnings, or simply because.</p></div><div className="occasion-tabs"><button className="active">Warmth</button><button>Celebration</button><button>Comfort</button><button>Just because</button></div></div><div className="gift-panel"><div><span className="eyebrow">The Eternal Warmth Keepsake Box</span><h3>A little luxury,<br/><em>beautifully held.</em></h3><p>A thoughtful edit with everything they need to feel wrapped in your care.</p><Link className="primary-button" href="/product/aurelius-heritage-bear">Build the keepsake box →</Link></div><img src={images.gift} alt="Eternal Warmth Keepsake Box"/></div></section></SectionReveal>
  <SectionReveal><section className="testimonial-section"><span className="eyebrow">Loved by 8,400+ collectors</span><h2>Hugs Around the World</h2><div className="quotes"><blockquote>“Brought tears to my sister&apos;s eyes.”<cite>— Eleanor L.</cite></blockquote><blockquote>“Architectural luxury for the bedroom.”<cite>— Marcus K.</cite></blockquote><blockquote>“The weighted calming touch really works.”<cite>— Claire L.</cite></blockquote></div></section></SectionReveal>
  <section className="society"><span className="eyebrow">A softer community</span><h2>Join the Keepsake Society</h2><p>Receive first access to new companions, quiet gifting notes,<br/>and invitations from the SoftHaven atelier.</p><Link className="primary-button" href="/contact">Join the society →</Link></section>
 </>; }
