import Link from 'next/link';
import type { Business } from '@/lib/business';
import type { PolicySection } from '@/components/policy-page';
import { paymentMethods } from '@/lib/checkout/payment-methods';
const contact = <Link href="/contact">Contact SoftHaven</Link>;
const section = (id: string, title: string, text: string): PolicySection => ({ id, title, body: <p>{text}</p> });
export const policyMeta = {
 'privacy-policy': { title: 'Privacy Policy', description: 'How customer information is collected, used and protected when shopping with SoftHaven Sri Lanka.' },
 'returns-refunds': { title: 'Returns, Refunds & Cancellation', description: 'Information about return requests, damaged items, refunds and order cancellations at SoftHaven.' },
 'shipping-delivery': { title: 'Shipping & Delivery', description: 'Delivery coverage, checkout shipping charges and guidance for receiving your SoftHaven order.' },
 'terms-conditions': { title: 'Terms & Conditions', description: 'The terms for using SoftHaven Sri Lanka and purchasing our plush companions online.' },
};
export type PolicyKey = keyof typeof policyMeta;
export function policySections(key: PolicyKey, b: Business): PolicySection[] {
 if (key === 'privacy-policy') return [
 section('introduction','Your information, with care','This policy explains how SoftHaven handles personal information when you browse, create an account, shop or contact us. The merchant responsible for this website is ' + b.registeredBusinessName + ', based in ' + b.country + '.'),
 {id:'information',title:'Information we collect',body:<><p>When you create an account or place an order, we use your name, email address, telephone number, delivery address, account details, purchased items, quantities, payment method and order/payment status. Saved addresses, favourites, reward records and reviews are used when you choose those features.</p><p>Our hosting and security services may process technical request information, including IP address and browser/device details, to operate and protect the website. We do not ask you to enter complete card numbers or CVV/CVC codes in SoftHaven forms.</p></>},
 section('use','How we use information','We use relevant information to validate orders and stock, calculate charges, arrange delivery, communicate order status, provide support, maintain accounts and saved addresses, administer rewards and reviews, prevent fraud or abuse, operate the website and keep necessary transaction records. Newsletter subscriptions are handled separately when you choose to subscribe.'),
 section('payments','Payment processing','Cash on Delivery is currently the enabled checkout method. If online payments are enabled in future, payment credentials will be handled by the selected third-party payment provider, which may include PayHere, under its own privacy and processing terms. SoftHaven does not collect or store complete card numbers or CVV/CVC credentials. Order and payment-status records may be retained to administer transactions and refunds.'),
 section('sharing','Service providers','Information necessary to operate the store may be handled by our hosting and database providers. Relevant delivery information is provided to delivery/courier services to fulfil orders. Where an online payment service is enabled, the necessary transaction information is supplied to that provider. Information may also be disclosed where required by applicable law. We do not publish customer delivery details as part of public product reviews.'),
 section('cookies','Cookies & local storage','Authentication uses cookies to maintain your session. Cart and favourite selections use browser local storage so they can persist on your device. These are functional technologies; disabling cookies or clearing local storage may sign you out or remove saved selections. The website does not currently use an advertising or analytics-cookie service. Your browser provides controls to clear or restrict stored data.'),
 section('security','Data security','We use access controls and technical protections intended to reduce unauthorized access and misuse. No internet service can guarantee absolute security. Keep your sign-in credentials private and contact us promptly if you believe your account has been accessed without permission.'),
 section('retention','Data retention','Information is kept for legitimate order fulfilment, support, accounting, legal and security purposes. Retention depends on the record and applicable obligations; we do not promise a fixed deletion period that has not been established. A deletion request may not remove records that must be retained lawfully.'),
 {id:'requests',title:'Your choices & requests',body:<p>{contact} to ask about access to, correction of or deletion of your personal information, or to withdraw a newsletter subscription. We may ask for enough information to verify your identity before handling an account-related request. Applicable legal rights are preserved.</p>},
 section('updates','Policy updates','Changes will be published on this page with an updated date. Review the current policy when using new store features or placing a new order.'),
 ];
 if (key === 'returns-refunds') return [
 section('returns','Returns & eligibility','Return request period: ' + b.returnEligibilityPeriod + '. Eligibility, original-condition/packaging requirements and any plush-toy hygiene restrictions: ' + b.returnEligibility + '. These merchant rules require confirmation; no arbitrary return deadline or hygiene exclusion is implied.'),
 {id:'request',title:'How to request a return',body:<><p>{contact} with your order number, the item concerned and the reason for the request. Please obtain return instructions before sending an item, so the correct destination and procedure can be confirmed.</p><p>Return destination: {b.returnAddress}. Keep your proof of purchase and any correspondence.</p></>},
 {id:'damaged',title:'Damaged, defective, incorrect or missing items',body:<p>{contact} promptly with your order number and a description of the issue. Photographs of the item, packaging and delivery label may help us assess damage or an incorrect shipment. For missing items, identify what was ordered and what arrived. Support must assess the appropriate remedy; this policy does not exclude rights available under applicable law.</p>},
 section('refunds','Refund assessment & processing','Where a return is required, the returned item is received and assessed before the decision is communicated. An approved refund is processed through a method appropriate to the original transaction. Card refunds, when card payments are enabled, should normally use the relevant gateway/card refund process. Cash-on-Delivery and other non-card payments may require a separately agreed refund method. Do not send complete card details to support.'),
 section('charges','Shipping charges','Treatment of original delivery charges and return shipping costs: ' + b.shippingRefunds + '. This must be confirmed by the merchant, including responsibility where an item is faulty or incorrect. No undisclosed deduction or blanket non-refundable shipping rule is established here.'),
 section('exchanges','Exchanges','Exchange availability and conditions: ' + b.exchanges + '. Contact support to confirm availability and any approved price or delivery difference before returning a product.'),
 section('excluded','Non-returnable items','Confirmed exclusions: ' + b.nonReturnableItems + '. No category is automatically excluded merely because it is a plush toy. Any exclusions must be clearly disclosed and must not remove rights that cannot lawfully be excluded.'),
 {id:'cancellation',title:'Cancellation Policy',body:<><p>Cancellation conditions and deadline: {b.cancellationConditions}.</p><p>{contact} with your order number and an explicit cancellation request. Whether fulfilment has started or the parcel has been dispatched may affect the available options; the merchant must confirm these operational rules. A paid cancellation approved for refund will follow the applicable refund process. Contacting support does not itself confirm cancellation.</p></>},
 section('timing','Refund completion times','Refund completion can depend on the original payment method, payment provider and financial institution. Support should communicate the approved amount and processing status. No exact bank/card settlement time is guaranteed by this page.'),
 ];
 if (key === 'shipping-delivery') return [
 section('areas','Delivery areas','Confirmed geographical coverage: ' + b.deliveryAreas + '. Checkout offers active delivery rates configured by the merchant for the selected destination. An address is not accepted for delivery merely because it can be typed into a form.'),
 section('charges','Shipping charges','Delivery charges are calculated from the active shipping rate selected in checkout. Applicable discounts and any free-delivery eligibility are included in your reviewed order total. The delivery charge and final total are displayed before the order is placed. Please review the delivery option and charge shown for your order.'),
 section('estimate','Estimated delivery time','Standard delivery estimate: ' + b.standardDeliveryEstimate + '. Estimates require merchant confirmation and are not guaranteed arrival dates.'),
 section('processing','Order processing','Normal processing time and fulfilment conditions: ' + b.orderProcessing + '. The order acknowledgement and account order information describe the recorded order status; an acknowledgement is not proof that delivery has occurred.'),
 section('delays','Delivery delays','Courier operations, weather, public holidays, remote locations and incomplete delivery information can affect delivery. If an order is delayed, contact support with its order number for the available status information.'),
 section('address','Accurate delivery information','Please check your recipient name, telephone number and full delivery address before placing the order. Contact support as soon as you notice an error. Address changes after fulfilment or dispatch may not be operationally possible; do not assume a change is confirmed until support responds.'),
 section('failed','Failed delivery','Failed-delivery, collection and redelivery arrangements: ' + b.failedDelivery + '. Any additional charge must be explained and agreed where applicable; no automatic redelivery fee is established by this policy.'),
 {id:'damage',title:'Damaged packages & support',body:<p>Keep the packaging where possible and {contact} with the order number and photographs of visible damage. See our <Link href="/returns-refunds#damaged">damaged-item guidance</Link> for the assessment process.</p>},
 ];
 return [
 section('acceptance','Acceptance of terms','These terms apply when you use SoftHaven or place an order. Read them alongside the linked privacy, delivery and returns policies. Merchant: ' + b.registeredBusinessName + '. Unconfirmed bracketed merchant details must be completed before this draft is published.'),
 section('use','Using the website','Use the website lawfully and provide accurate information. If you cannot enter a binding purchase agreement yourself, involve a parent, guardian or other authorized person. Do not impersonate another customer or place orders without permission.'),
 section('accounts','Customer accounts','Keep account credentials private, maintain accurate contact details and notify support of suspected unauthorized access. Account tools may provide saved addresses, order information, favourites and rewards. Reward availability follows the store’s configured rules; no benefit is guaranteed merely by having an account.'),
 section('products','Product information','We make reasonable efforts to present accurate product descriptions, photographs, variants and availability. Colours may appear slightly different across displays and devices. Ask support about any essential specification before purchasing. Stock availability is validated when the order is processed.'),
 section('pricing','Prices & promotions','Store currency: ' + b.defaultCurrency + ' (Sri Lankan rupees). Product prices and available promotions are shown on the website. Checkout calculates the applicable discounts, delivery charge and total before confirmation. If a genuine pricing error is discovered, we may contact you to correct the order or arrange cancellation and any applicable refund; we will not silently impose a higher charge.'),
 section('orders','Orders & confirmation','The purchasing process is product selection, cart review and checkout. An order is created after its details, availability and charges have been checked. A successful checkout shows an order reference and recorded total. An acknowledgement does not guarantee unavailable stock. Orders may be declined or cancelled for legitimate reasons such as unavailable stock, invalid payment or suspected fraud, with any applicable refund addressed through support.'),
 section('payment','Payment methods','Currently enabled payment methods: ' + paymentMethods.filter(m=>m.enabled).map(m=>m.title).join(', ') + '. Other displayed methods are unavailable until configured. PayHere online payment is not currently active. If enabled, online payment credentials will be handled through the payment provider, rather than SoftHaven collecting complete card numbers or CVV/CVC codes.'),
 {id:'delivery',title:'Shipping & delivery',body:<p>Read the <Link href="/shipping-delivery">Shipping & Delivery Policy</Link> for coverage, estimates, address requirements and delivery charges. The checkout quote is the source for the charge applicable to your order.</p>},
 {id:'returns',title:'Returns, refunds & cancellation',body:<p>Read the <Link href="/returns-refunds">Returns & Refunds Policy</Link>, including its independent <Link href="/returns-refunds#cancellation">Cancellation Policy</Link>. Applicable consumer rights are not excluded by these terms.</p>},
 section('ownership','Intellectual property','The SoftHaven name, logo, owned photography, graphics, website design and text belong to their respective rights holders. You may use the website to browse and purchase, but may not copy or exploit protected content commercially without permission. Third-party rights remain with their owners.'),
 section('abuse','Prohibited use','Do not attempt unauthorized access, disrupt the service, upload malicious material, abuse customer or administrative tools, conduct fraudulent transactions or use the website unlawfully. We may restrict abusive access while respecting applicable law.'),
 {id:'providers',title:'Third-party services & privacy',body:<p>Hosting, database, delivery and any enabled payment providers operate under their own applicable terms. Necessary information handling is described in the <Link href="/privacy-policy">Privacy Policy</Link>. An external link does not mean SoftHaven owns or endorses that service.</p>},
 section('liability','Responsibility & consumer rights','We take reasonable care in operating the store but cannot promise uninterrupted website availability or absolute security. Responsibility for losses is determined under applicable law. Nothing in these terms excludes liability or consumer rights that cannot legally be excluded.'),
 section('law','Changes & governing law','Updated terms will be published here with a revised date. Changes are not intended to retrospectively remove rights attached to an existing purchase. These terms are governed by applicable laws of Sri Lanka, without excluding mandatory protections that apply to a customer.'),
 {id:'contact',title:'Contact information',body:<p>{contact} for questions about these terms, your order or a policy. Merchant identity and available support details are listed below.</p>},
 ];
}
