import { z } from "zod";
const text = z.string().max(5000);
const short = z.string().trim().min(1).max(200);
const money = z.preprocess(
  (v) => (v === "" ? undefined : v),
  z.coerce.number().min(0).max(100000000),
);
const integer = z.coerce.number().int();
const link = z
  .string()
  .max(2000)
  .refine(
    (v) => !v || /^\/(?!\/)/.test(v) || /^https:\/\//.test(v),
    "Use a local path or HTTPS URL",
  );
const opt = (v: z.ZodType) => v.nullable().optional();
export type Field = {
  label: string;
  type?:
    | "text"
    | "textarea"
    | "number"
    | "checkbox"
    | "select"
    | "json"
    | "datetime-local";
  options?: string[];
  required?: boolean;
};
export type Resource = {
  title: string;
  table: string;
  area: string;
  columns: string[];
  search: string;
  fields: Record<string, Field>;
  schema: z.ZodObject;
  readonly?: boolean;
  archive?: string;
};
function define(
  title: string,
  table: string,
  area: string,
  columns: string[],
  search: string,
  fields: Record<string, Field>,
  shape: Record<string, z.ZodType>,
  extras: Partial<Resource> = {},
): Resource {
  return {
    title,
    table,
    area,
    columns,
    search,
    fields,
    schema: z.object(shape).strict(),
    ...extras,
  };
}
const baseFields = {
  name: { label: "Name", required: true },
  slug: { label: "Slug", required: true },
  description: { label: "Description", type: "textarea" as const },
  image: { label: "Image URL" },
  active: { label: "Active", type: "checkbox" as const },
  sort_order: { label: "Sort order", type: "number" as const },
  seo_title: { label: "SEO title" },
  seo_description: { label: "SEO description", type: "textarea" as const },
};
const baseShape = {
  name: short,
  slug: short.regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  description: text.optional(),
  image: opt(link),
  active: z.boolean().optional(),
  sort_order: integer.optional(),
  seo_title: opt(text),
  seo_description: opt(text),
};
export const resources: Record<string, Resource> = {
  products: define(
    "Products",
    "products",
    "products",
    ["name", "sku", "price", "status", "featured"],
    "name",
    {
      name: { label: "Name", required: true },
      sku: { label: "SKU" },
      slug: { label: "Slug", required: true },
      description: { label: "Full description", type: "textarea" },
      short_description: { label: "Short description", type: "textarea" },
      category_id: { label: "Category" },
      image: { label: "Cover image URL" },
      images: { label: "Gallery image URLs", type: "json" },
      details: { label: "Product details", type: "json" },
      price: { label: "Price (LKR)", type: "number", required: true },
      compare_at: { label: "Compare-at price", type: "number" },
      cost_price: { label: "Cost price", type: "number" },
      status: {
        label: "Status",
        type: "select",
        options: ["draft", "published", "archived"],
      },
      featured: { label: "Featured on homepage", type: "checkbox" },
      new_arrival: { label: "New arrival", type: "checkbox" },
      best_seller: { label: "Best seller", type: "checkbox" },
      seo_title: { label: "SEO title" },
      seo_description: { label: "SEO description", type: "textarea" },
    },
    {
      name: short,
      sku: opt(short),
      slug: short.regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
      description: text.optional(),
      short_description: text.optional(),
      category_id: opt(z.uuid()),
      image: opt(link),
      images: z.array(link).max(30).optional(),
      details: z.array(text).max(30).optional(),
      price: money,
      compare_at: opt(money),
      cost_price: opt(money),
      status: z.enum(["draft", "published", "archived"]).optional(),
      featured: z.boolean().optional(),
      new_arrival: z.boolean().optional(),
      best_seller: z.boolean().optional(),
      seo_title: opt(text),
      seo_description: opt(text),
    },
    { archive: "status" },
  ),
  categories: define(
    "Categories",
    "categories",
    "products",
    ["name", "slug", "active", "sort_order"],
    "name",
    baseFields,
    baseShape,
    { archive: "active" },
  ),
  collections: define(
    "Collections",
    "collections",
    "products",
    ["name", "slug", "active", "featured", "sort_order"],
    "name",
    { ...baseFields, featured: { label: "Featured", type: "checkbox" } },
    { ...baseShape, featured: z.boolean().optional() },
    { archive: "active" },
  ),
  variants: define(
    "Colour variants",
    "product_variants",
    "products",
    ["product_id", "color", "sku", "price", "stock", "active"],
    "color",
    {
      product_id: { label: "Product", required: true },
      color: { label: "Colour name", required: true },
      color_hex: { label: "Colour hex" },
      sku: { label: "Variant SKU" },
      image: { label: "Variant image URL" },
      price: { label: "Price override (LKR)", type: "number" },
      compare_at: { label: "Compare-at override", type: "number" },
      low_stock_threshold: { label: "Low-stock threshold", type: "number" },
      active: { label: "Active", type: "checkbox" },
      sort_order: { label: "Sort order", type: "number" },
    },
    {
      product_id: short,
      color: short,
      color_hex: opt(z.string().regex(/^#[0-9a-fA-F]{6}$/)),
      sku: opt(short),
      image: opt(link),
      price: opt(money),
      compare_at: opt(money),
      low_stock_threshold: integer.min(0).optional(),
      active: z.boolean().optional(),
      sort_order: integer.optional(),
    },
    { archive: "active" },
  ),
  "product-collections": define(
    "Collection assignments",
    "product_collections",
    "products",
    ["product_id", "collection_id"],
    "product_id",
    {
      product_id: { label: "Product", required: true },
      collection_id: { label: "Collection", required: true },
    },
    { product_id: short, collection_id: z.uuid() },
  ),
  inventory: define(
    "Inventory",
    "product_variants",
    "inventory",
    ["product_id", "color", "sku", "stock", "low_stock_threshold"],
    "color",
    {},
    {},
    { readonly: true },
  ),
  movements: define(
    "Inventory movements",
    "inventory_movements",
    "inventory",
    [
      "variant_id",
      "quantity_change",
      "previous_quantity",
      "new_quantity",
      "reason",
      "created_at",
    ],
    "reason",
    {},
    {},
    { readonly: true },
  ),
  orders: define(
    "Orders",
    "orders",
    "orders",
    [
      "order_number",
      "email",
      "total",
      "payment_status",
      "status",
      "created_at",
    ],
    "email",
    {},
    {},
    { readonly: true },
  ),
  customers: define(
    "Customers",
    "profiles",
    "customers",
    ["name", "email", "phone", "active", "created_at"],
    "email",
    {
      name: { label: "Name" },
      phone: { label: "Phone" },
      notes: { label: "Internal notes", type: "textarea" },
      active: { label: "Account active", type: "checkbox" },
    },
    { name: text, phone: opt(text), notes: opt(text), active: z.boolean() },
  ),
  addresses: define(
    "Customer addresses",
    "customer_addresses",
    "customers",
    ["customer_id", "name", "city", "country"],
    "name",
    {},
    {},
    { readonly: true },
  ),
  reviews: define(
    "Reviews",
    "reviews",
    "reviews",
    [
      "product_id",
      "rating",
      "title",
      "status",
      "verified_purchase",
      "created_at",
    ],
    "title",
    {
      status: {
        label: "Moderation status",
        type: "select",
        options: ["pending", "approved", "rejected", "hidden"],
      },
      reply: { label: "Store reply", type: "textarea" },
    },
    {
      status: z.enum(["pending", "approved", "rejected", "hidden"]),
      reply: opt(text),
    },
    { archive: "status" },
  ),
  coupons: define(
    "Coupons",
    "coupons",
    "marketing",
    ["code", "kind", "value", "active", "ends_at"],
    "code",
    {
      code: { label: "Code (uppercase)", required: true },
      description: { label: "Description", type: "textarea" },
      kind: {
        label: "Discount type",
        type: "select",
        options: ["percentage", "fixed", "free_shipping"],
      },
      value: { label: "Discount value", type: "number" },
      min_order: { label: "Minimum order", type: "number" },
      max_discount: { label: "Maximum discount", type: "number" },
      usage_limit: { label: "Total usage limit", type: "number" },
      per_customer_limit: { label: "Per-customer limit", type: "number" },
      first_order_only: { label: "First order only", type: "checkbox" },
      active: { label: "Active", type: "checkbox" },
      starts_at: { label: "Starts", type: "datetime-local" },
      ends_at: { label: "Expires", type: "datetime-local" },
      product_ids: { label: "Product IDs", type: "json" },
      category_ids: { label: "Category IDs", type: "json" },
      collection_ids: { label: "Collection IDs", type: "json" },
      customer_ids: { label: "Allowed customer IDs", type: "json" },
    },
    {
      code: short.regex(/^[A-Z0-9_-]+$/),
      description: text.optional(),
      kind: z.enum(["percentage", "fixed", "free_shipping"]),
      value: money.optional(),
      min_order: money.optional(),
      max_discount: opt(money),
      usage_limit: opt(integer.min(1)),
      per_customer_limit: integer.min(1).optional(),
      first_order_only: z.boolean().optional(),
      active: z.boolean().optional(),
      starts_at: opt(z.iso.datetime()),
      ends_at: opt(z.iso.datetime()),
      product_ids: z.array(short).optional(),
      category_ids: z.array(z.uuid()).optional(),
      collection_ids: z.array(z.uuid()).optional(),
      customer_ids: z.array(z.uuid()).optional(),
    },
    { archive: "active" },
  ),
  promotions: define(
    "Promotions",
    "promotions",
    "marketing",
    ["name", "coupon_id", "active", "starts_at", "ends_at"],
    "name",
    {
      name: { label: "Campaign name", required: true },
      description: { label: "Description", type: "textarea" },
      coupon_id: { label: "Associated coupon" },
      active: { label: "Active", type: "checkbox" },
      starts_at: { label: "Starts", type: "datetime-local" },
      ends_at: { label: "Ends", type: "datetime-local" },
    },
    {
      name: short,
      description: text.optional(),
      coupon_id: opt(z.uuid()),
      active: z.boolean().optional(),
      starts_at: opt(z.iso.datetime()),
      ends_at: opt(z.iso.datetime()),
    },
    { archive: "active" },
  ),
  rewards: define(
    "Reward ledger",
    "reward_transactions",
    "rewards",
    ["customer_id", "points", "type", "reason", "created_at"],
    "reason",
    {},
    {},
    { readonly: true },
  ),
  "reward-settings": define(
    "Loyalty settings",
    "reward_settings",
    "rewards",
    ["id", "enabled", "earn_per_currency", "point_value"],
    "id",
    {
      enabled: { label: "Enable rewards", type: "checkbox" },
      earn_per_currency: { label: "Points earned per LKR", type: "number" },
      point_value: { label: "LKR value of one point", type: "number" },
      minimum_redemption: {
        label: "Minimum points redemption",
        type: "number",
      },
      maximum_redemption: {
        label: "Maximum points redemption",
        type: "number",
      },
      expiry_days: { label: "Expiry days", type: "number" },
      welcome_bonus: { label: "Welcome bonus", type: "number" },
      review_bonus: { label: "Approved review bonus", type: "number" },
    },
    {
      enabled: z.boolean(),
      earn_per_currency: money,
      point_value: money,
      minimum_redemption: integer.min(1),
      maximum_redemption: opt(integer.min(1)),
      expiry_days: opt(integer.min(1)),
      welcome_bonus: integer.min(0),
      review_bonus: integer.min(0),
    },
  ),
  shipping: define(
    "Shipping zones",
    "shipping_zones",
    "settings",
    ["name", "countries", "districts", "active"],
    "name",
    {
      name: { label: "Zone name", required: true },
      countries: { label: "Country codes", type: "json" },
      districts: { label: "Districts (empty means all)", type: "json" },
      active: { label: "Active", type: "checkbox" },
    },
    {
      name: short,
      countries: z.array(z.string().length(2)).min(1),
      districts: z.array(short).optional(),
      active: z.boolean().optional(),
    },
    { archive: "active" },
  ),
  "shipping-rates": define(
    "Shipping rates",
    "shipping_rates",
    "settings",
    ["name", "zone_id", "rate", "free_over", "active"],
    "name",
    {
      name: { label: "Method name", required: true },
      zone_id: { label: "Shipping zone", required: true },
      rate: { label: "Rate (LKR)", type: "number", required: true },
      free_over: { label: "Free shipping above LKR", type: "number" },
      active: { label: "Active", type: "checkbox" },
    },
    {
      name: short,
      zone_id: z.uuid(),
      rate: money,
      free_over: opt(money),
      active: z.boolean().optional(),
    },
    { archive: "active" },
  ),
  newsletter: define(
    "Newsletter subscribers",
    "newsletter_subscribers",
    "marketing",
    ["email", "name", "status", "source", "created_at"],
    "email",
    {
      status: {
        label: "Status",
        type: "select",
        options: ["subscribed", "unsubscribed"],
      },
    },
    { status: z.enum(["subscribed", "unsubscribed"]) },
  ),
  campaigns: define(
    "Newsletter campaigns",
    "newsletter_campaigns",
    "marketing",
    ["name", "subject", "status", "created_at"],
    "name",
    {
      name: { label: "Campaign name", required: true },
      subject: { label: "Subject", required: true },
      preview_text: { label: "Preview text" },
      content: { label: "Content", type: "textarea" },
      status: {
        label: "Status",
        type: "select",
        options: ["draft", "cancelled"],
      },
    },
    {
      name: short,
      subject: short,
      preview_text: opt(text),
      content: text,
      status: z.enum(["draft", "cancelled"]),
    },
  ),
  "content/slideshow": define(
    "Landing slideshow",
    "hero_slides",
    "content",
    ["title", "active", "sort_order", "starts_at", "ends_at"],
    "title",
    {
      title: { label: "Title", required: true },
      subtitle: { label: "Subtitle" },
      description: { label: "Description", type: "textarea" },
      desktop_image: { label: "Desktop image URL", required: true },
      mobile_image: { label: "Mobile image URL" },
      alt_text: { label: "Image alt text", required: true },
      badge: { label: "Badge" },
      cta_label: { label: "CTA label" },
      cta_url: { label: "CTA URL" },
      secondary_cta_label: { label: "Secondary CTA label" },
      secondary_cta_url: { label: "Secondary CTA URL" },
      active: { label: "Active", type: "checkbox" },
      sort_order: { label: "Sort order", type: "number" },
      starts_at: { label: "Starts", type: "datetime-local" },
      ends_at: { label: "Ends", type: "datetime-local" },
    },
    {
      title: short,
      subtitle: text.optional(),
      description: text.optional(),
      desktop_image: link,
      mobile_image: opt(link),
      alt_text: short,
      badge: opt(text),
      cta_label: short.optional(),
      cta_url: link.optional(),
      secondary_cta_label: opt(text),
      secondary_cta_url: opt(link),
      active: z.boolean().optional(),
      sort_order: integer.optional(),
      starts_at: opt(z.iso.datetime()),
      ends_at: opt(z.iso.datetime()),
    },
    { archive: "active" },
  ),
  "content/homepage": define(
    "Homepage sections",
    "homepage_sections",
    "content",
    ["id", "title", "active", "sort_order"],
    "title",
    {
      title: { label: "Headline", required: true },
      eyebrow: { label: "Eyebrow" },
      highlight: { label: "Highlight" },
      description: { label: "Description", type: "textarea" },
      image: { label: "Image URL" },
      cta_label: { label: "CTA label" },
      cta_url: { label: "CTA URL" },
      active: { label: "Enabled", type: "checkbox" },
      sort_order: { label: "Sort order", type: "number" },
    },
    {
      title: short,
      eyebrow: opt(text),
      highlight: opt(text),
      description: opt(text),
      image: opt(link),
      cta_label: opt(text),
      cta_url: opt(link),
      active: z.boolean().optional(),
      sort_order: integer.optional(),
    },
    { archive: "active" },
  ),
  navigation: define(
    "Navigation & footer links",
    "site_navigation",
    "content",
    ["label", "url", "placement", "active", "sort_order"],
    "label",
    {
      label: { label: "Label", required: true },
      url: { label: "URL", required: true },
      placement: {
        label: "Placement",
        type: "select",
        options: ["header", "footer"],
      },
      active: { label: "Enabled", type: "checkbox" },
      sort_order: { label: "Sort order", type: "number" },
    },
    {
      label: short,
      url: link,
      placement: z.enum(["header", "footer"]),
      active: z.boolean().optional(),
      sort_order: integer.optional(),
    },
    { archive: "active" },
  ),
  settings: define(
    "Store settings",
    "site_settings",
    "settings",
    ["id", "value", "public"],
    "id",
    { value: { label: "Settings values", type: "json" } },
    { value: z.record(z.string(), z.union([text, z.boolean(), money])) },
  ),
  users: define(
    "Administrators",
    "admin_users",
    "users",
    ["id", "role", "active", "created_at"],
    "role",
    {
      id: { label: "Confirmed customer", required: true },
      role: {
        label: "Role",
        type: "select",
        options: [
          "SUPER_ADMIN",
          "ADMIN",
          "MANAGER",
          "ORDER_MANAGER",
          "PRODUCT_MANAGER",
          "CONTENT_EDITOR",
          "CUSTOMER_SUPPORT",
          "MARKETING",
          "REPORT_VIEWER",
        ],
      },
      active: { label: "Active", type: "checkbox" },
    },
    {
      id: z.uuid(),
      role: z.enum([
        "SUPER_ADMIN",
        "ADMIN",
        "MANAGER",
        "ORDER_MANAGER",
        "PRODUCT_MANAGER",
        "CONTENT_EDITOR",
        "CUSTOMER_SUPPORT",
        "MARKETING",
        "REPORT_VIEWER",
      ]),
      active: z.boolean(),
    },
    { archive: "active" },
  ),
  audit: define(
    "Audit log",
    "audit_logs",
    "reports",
    ["actor_id", "action", "entity_type", "entity_id", "created_at"],
    "entity_type",
    {},
    {},
    { readonly: true },
  ),
  media: define(
    "Media library",
    "media_assets",
    "media",
    ["name", "url", "alt_text", "mime_type", "size_bytes"],
    "name",
    { alt_text: { label: "Alternative text" } },
    { alt_text: text },
  ),
  notifications: define(
    "Notifications",
    "notifications",
    "notifications",
    ["type", "title", "entity_id", "read", "created_at"],
    "title",
    {},
    {},
    { readonly: true },
  ),
};
export function allowed(role: string, area: string) {
  if (area === "notifications")
    return [
      "SUPER_ADMIN",
      "ADMIN",
      "MANAGER",
      "ORDER_MANAGER",
      "PRODUCT_MANAGER",
      "CONTENT_EDITOR",
      "CUSTOMER_SUPPORT",
      "MARKETING",
      "REPORT_VIEWER",
    ].includes(role);
  return (
    role === "SUPER_ADMIN" ||
    (role === "ADMIN" && area !== "users") ||
    (role === "MANAGER" && !["users", "settings"].includes(area)) ||
    (
      {
        PRODUCT_MANAGER: ["products", "inventory", "media"],
        ORDER_MANAGER: ["orders", "customers"],
        CONTENT_EDITOR: ["content", "media"],
        CUSTOMER_SUPPORT: ["customers", "reviews"],
        MARKETING: ["marketing", "reviews", "rewards"],
        REPORT_VIEWER: ["reports"],
      } as Record<string, string[]>
    )[role]?.includes(area) ||
    false
  );
}
